package com.levi.rappimanager.domain.enumeration;

public enum RestaurantCategory {

    BRAZILIAN_FOOD, HEALTHY, PACKED_LUNCH, FROZEN_FOOD, SNACK, CHINESE_FOOD,
    MEAT, ITALIAN_FOOD, SEAFOOD, PIZZA, JAPONESE_FOOD, FAST_KITCHEN, ICE_CREAM,
    ACAI, CANDY_AND_CAKE, FRIED_FOOD, DRINK, CONVENIENCE, SOUP_AND_BROTH

}
